"""Add updated_at to students table

Revision ID: c7a9750178cd
Revises: 46e53e0a6e82
Create Date: 2024-12-22 14:58:40.223386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a9750178cd'
down_revision: Union[str, None] = '46e53e0a6e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'updated_at')
    # ### end Alembic commands ###
